
create table hackers (
  name varchar primary key,
  followers integer,
  repos integer,
  location varchar,
  updated timestamp
);

create table updates (
  update_id varchar primary key,
  author varchar,
  date timestamp,
  title varchar,
  content text,
  media varchar 
);

create table blog_posts (
  blog varchar,
  href varchar unique,
  title varchar,
  author varchar,
  date timestamp,
  summary text
);
